### ISSUE TITLE
README.md link failed

### ISSUE THREAD

**Issue by GreenMashimaro** [vikadata/awesome-vikadata#4]
# Problem Description

## 点击：《维格表开发者中心 - 小程序》
![image](https://user-images.githubusercontent.com/23225539/185868917-bdaa12f8-54ca-4c4b-8dc8-747dca50fb53.png)

## 跳转链接如下：
![image](https://user-images.githubusercontent.com/23225539/185869239-5a58f08c-febc-4b99-9d74-92420629c604.png)

**Comment by Niko030303** [comment]
你好，感谢指出错误，我们已完成订正。新的跳转链接为：https://vika.cn/developers/widget/quick-start

**Comment by GreenMashimaro** [comment]
thanks, very efficient update link.
